// ────────────────────────────────────────────────────────────────────────────
// _reactive — internal compiler plumbing for reactive data binding
//
// This module is NOT part of the public API. The underscore prefix signals
// that it is reserved for compiler-generated code.
//
// The CLI's reactive transformer emits calls to:
//   _reactive.compiled()     — pre-computed C++ reactive nodes
//   _reactive.slotted()      — slot-substituted reactive nodes
//   _reactive.derivedMemo()  — explicit C++ memo construction
// ────────────────────────────────────────────────────────────────────────────

import { ReactiveNode } from './reactive-node';
import type { ExpressionDependency } from './reactive-node';
import { registerReactiveNode } from './hooks/useReactiveScope';

// ────────────────────────────────────────────────────────────────────────────
// Library format version validation
// ────────────────────────────────────────────────────────────────────────────

/** Format versions this SDK can consume. */
export const SUPPORTED_FORMAT_VERSIONS: readonly number[] = [1];

/**
 * Validate that a compiled library's format version is supported by this SDK.
 * Throws a clear error if the version is missing or incompatible.
 *
 * Libraries stamp `__espcompose_format__` into their entry point at build time.
 * Call this at import time to catch version mismatches early.
 */
export function validateLibraryFormat(version: unknown): void {
  if (typeof version !== 'number') {
    throw new Error(
      'This ESPCompose library was not compiled with format versioning. ' +
      'Rebuild the library with the latest ESPCompose CLI (`espcompose library`).',
    );
  }
  if (!SUPPORTED_FORMAT_VERSIONS.includes(version)) {
    throw new Error(
      `This ESPCompose library was compiled with format v${version}, ` +
      `but this SDK supports format v${SUPPORTED_FORMAT_VERSIONS.join(', v')}. ` +
      'Please rebuild the library with a compatible ESPCompose CLI version.',
    );
  }
}

export const _reactive = {

  /**
   * Create a ReactiveNode from pre-computed C++ metadata.
   *
   * This is the compile-time entry point — the CLI's reactive transformer
   * AST-compiles expressions to C++ and injects calls to this method.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  compiled<T>(meta: {
    cpp: string;
    type: string;
    deps: Array<{
      signalName: string;
      sourceId: string;
      triggerType: string;
      sourceDomain: string;
      cppType: string;
      sourceType?: string;
    }>;
  }): ReactiveNode<T> {
    const dependencies: ExpressionDependency[] = meta.deps.map(d => ({
      sourceId: d.sourceId,
      triggerType: d.triggerType,
      sourceDomain: d.sourceDomain,
      cppSignalName: d.signalName,
      cppType: d.cppType,
      sourceType: (d.sourceType as 'ha_entity' | 'theme' | undefined),
    }));

    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies,
      cppExpression: meta.cpp,
      cppReturnType: meta.type,
    });

    registerReactiveNode(node);
    return node;
  },

  /**
   * Create a ReactiveNode from a C++ template with slot placeholders.
   *
   * The compiler emits `__$$SLOT_N$$__` placeholders for Signal<T>-typed
   * subexpressions that can't be resolved statically. At runtime this method
   * substitutes the placeholders with actual signal names and C++ types
   * from the provided ReactiveNode arguments.
   *
   * Also replaces `__$$SLOT_TYPE_N$$__` in `meta.type` with the signal's
   * C++ type — used when the compiler can't infer the type statically.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  slotted<R>(
    meta: { cpp: string; type: string; slots: number },
    ...signals: unknown[]
  ): ReactiveNode<R> {
    let cppExpr = meta.cpp;
    let cppType = meta.type;
    const allDeps: ExpressionDependency[] = [];

    for (let i = 0; i < meta.slots; i++) {
      const sig = signals[i] as ReactiveNode<unknown> | undefined;
      if (!sig) continue;
      const sigName = sig.cppSignalName ?? sig.dependencies[0]?.cppSignalName;
      if (sigName) {
        cppExpr = cppExpr.replace(
          new RegExp(`__\\$\\$SLOT_${i}\\$\\$__\\.get\\(\\)`, 'g'),
          `${sigName}.get()`,
        );
      }
      const sigCppType = sig.cppType ?? sig.dependencies[0]?.cppType;
      if (sigCppType) {
        cppType = cppType.replace(`__$$SLOT_TYPE_${i}$$__`, sigCppType);
      }
      allDeps.push(...sig.dependencies);
    }

    return _reactive.derivedMemo<R>({
      cppExpression: cppExpr,
      cppReturnType: cppType,
      dependencies: allDeps,
    });
  },

  /**
   * Create a derived memo with an explicit C++ expression.
   *
   * Use this when a C++ expression is already known and doesn't need
   * to go through the compiler transform (e.g. internal generated code).
   */
  derivedMemo<T>(opts: {
    cppExpression: string;
    cppReturnType: string;
    dependencies: ExpressionDependency[];
  }): ReactiveNode<T> {
    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies: opts.dependencies,
      cppExpression: opts.cppExpression,
      cppReturnType: opts.cppReturnType,
    });
    registerReactiveNode(node);
    return node;
  },
};
