// ────────────────────────────────────────────────────────────────────────────
// bind — device-reactive data binding namespace
//
// The `bind` namespace provides APIs for declaring reactive data sources
// and derived values that will be wired into the device firmware. These
// APIs run conceptually on the device — they establish reactive
// relationships that are lowered to ESPHome triggers or the C++ reactive
// runtime.
//
// Phase E: full ReactiveNode + dependency tracking.
//
// Usage:
//   import { bind } from '@esphome/compose';
//   const light = bind.haEntity('light.kitchen');
//   const status = bind.memo(() => light.isOn() ? 'ON' : 'OFF');
// ────────────────────────────────────────────────────────────────────────────

import { importHAEntity } from './hooks/useHAEntity';
import {
  ReactiveNode,
  isReactiveNode,
  startTracking,
  stopTracking,
} from './reactive-node';
import type { ExpressionDependency } from './reactive-node';
import { registerReactiveNode } from './hooks/useReactiveScope';

import type {
  LightBinding,
  SensorBinding,
  BinarySensorBinding,
  SwitchBinding,
  FanBinding,
  CoverBinding,
} from './ha-bindings';

// ── BindProp<T>: the reactive prop type alias ──────────────────────────────

/**
 * A prop value that can be static, a reactive node, or a reactive function.
 * Component authors use this to declare which props support reactive binding.
 */
export type BindProp<T> = T | (() => T) | ReactiveNode<T>;

// ── HAEntityBinding type alias ─────────────────────────────────────────────

/**
 * Maps HA entity domain strings to their binding interface types.
 */
export interface HAEntityBindingMap {
  light: LightBinding;
  sensor: SensorBinding;
  binary_sensor: BinarySensorBinding;
  switch: SwitchBinding;
  fan: FanBinding;
  cover: CoverBinding;
}

/**
 * Resolve an HA domain string to the corresponding binding type.
 */
export type HAEntityBinding<D extends keyof HAEntityBindingMap> = HAEntityBindingMap[D];

// ── bind namespace ─────────────────────────────────────────────────────────

export const bind = {
  /**
   * Bind a Home Assistant entity by entity ID.
   * Returns a domain-typed binding with reactive properties and action methods.
   *
   * This is a re-export of `importHAEntity()` under the `bind` namespace.
   */
  haEntity: importHAEntity,

  /**
   * Create a ReactiveNode from pre-computed C++ metadata.
   *
   * This is the compile-time entry point — the CLI's reactive transformer
   * AST-compiles expressions to C++ and injects calls to this method.
   * No fn.toString(), no regex codegen, no access recording needed.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  __compiled<T>(meta: {
    cpp: string;
    type: string;
    deps: Array<{
      signalName: string;
      sourceId: string;
      triggerType: string;
      sourceDomain: string;
      cppType: string;
      sourceType?: string;
    }>;
  }): ReactiveNode<T> {
    const dependencies: ExpressionDependency[] = meta.deps.map(d => ({
      sourceId: d.sourceId,
      triggerType: d.triggerType,
      sourceDomain: d.sourceDomain,
      cppSignalName: d.signalName,
      cppType: d.cppType,
      sourceType: (d.sourceType as 'ha_entity' | 'theme' | undefined),
    }));

    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies,
      cppExpression: meta.cpp,
      cppReturnType: meta.type,
    });

    registerReactiveNode(node);
    return node;
  },

  /**
   * Create a ReactiveNode from a C++ template with slot placeholders.
   *
   * The compiler emits `__$$SLOT_N$$__` placeholders for Signal<T>-typed
   * subexpressions that can't be resolved statically. At runtime this method
   * substitutes the placeholders with actual signal names and C++ types
   * from the provided ReactiveNode arguments.
   *
   * Also replaces `__$$SLOT_TYPE_N$$__` in `meta.type` with the signal's
   * C++ type — used when the compiler can't infer the type statically.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  __slotted<R>(
    meta: { cpp: string; type: string; slots: number },
    // Accepts Signal<T> (branded phantom type) or ReactiveNode<T> — at runtime
    // both are ReactiveNode instances. The `unknown` allows the compiler-emitted
    // expressions to pass type-checking when typed as Signal<T>.
    ...signals: unknown[]
  ): ReactiveNode<R> {
    let cppExpr = meta.cpp;
    let cppType = meta.type;
    const allDeps: ExpressionDependency[] = [];

    for (let i = 0; i < meta.slots; i++) {
      const sig = signals[i] as ReactiveNode<unknown> | undefined;
      if (!sig) continue;
      const sigName = sig.cppSignalName ?? sig.dependencies[0]?.cppSignalName;
      if (sigName) {
        cppExpr = cppExpr.replace(
          new RegExp(`__\\$\\$SLOT_${i}\\$\\$__\\.get\\(\\)`, 'g'),
          `${sigName}.get()`,
        );
      }
      const sigCppType = sig.cppType ?? sig.dependencies[0]?.cppType;
      if (sigCppType) {
        cppType = cppType.replace(`__$$SLOT_TYPE_${i}$$__`, sigCppType);
      }
      allDeps.push(...sig.dependencies);
    }

    return bind.derivedMemo<R>({
      cppExpression: cppExpr,
      cppReturnType: cppType,
      dependencies: allDeps,
    });
  },

  /**
   * Create a memoized derived value from one or more reactive sources.
   *
   * In the normal build pipeline, the CLI's reactive transformer replaces
   * bind.memo() calls with bind.__compiled() before this code runs.
   * This runtime fallback handles:
   *   - Pure computations (no reactive deps) — returns the value directly
   *   - Leftover reactive calls not caught by the compiler — creates
   *     a ReactiveNode with dependency tracking only
   */
  memo<T>(fn: () => T): T | ReactiveNode<T> {
    startTracking();
    const value = fn();
    const deps = stopTracking();

    if (deps.length === 0) {
      // Pure computation — no reactive dependencies, return as-is
      return value;
    }

    // Infer C++ return type from the JS value
    let cppReturnType: string | undefined;
    if (typeof value === 'string') cppReturnType = 'std::string';
    else if (typeof value === 'number') cppReturnType = 'float';
    else if (typeof value === 'boolean') cppReturnType = 'bool';

    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies: deps,
      cppExpression: '0 /* uncompiled – AST compiler should have handled this */',
      cppReturnType,
    });

    registerReactiveNode(node);
    return node;
  },

  /**
   * Register a side-effect that runs when reactive sources change.
   *
   * The callback is executed once to capture dependencies. During lowering,
   * it becomes an Effect node in the C++ reactive runtime.
   */
  effect(fn: () => void): void {
    startTracking();
    fn();
    const deps = stopTracking();

    if (deps.length > 0) {
      const node = new ReactiveNode<void>({
        kind: 'effect',
        dependencies: deps,
        cppExpression: '0 /* uncompiled – AST compiler should have handled this */',
      });

      registerReactiveNode(node);
    }
  },

  /**
   * Normalize a prop value that may be static, reactive node, or reactive function.
   *
   * - `ReactiveNode<T>` → pass through (already tracked)
   * - `() => T` → evaluate with dependency tracking → ReactiveNode or literal
   * - `T` → literal (no reactivity)
   */
  expr<T>(prop: BindProp<T>): T | ReactiveNode<T> {
    if (isReactiveNode(prop)) {
      return prop as ReactiveNode<T>;
    }
    if (typeof prop === 'function') {
      return bind.memo(prop as () => T);
    }
    return prop as T;
  },

  /**
   * Create a derived memo with an explicit C++ expression.
   *
   * Use this when a C++ expression is already known and doesn't need
   * to go through the compiler transform (e.g. internal generated code).
   *
   * @example
   * bind.derivedMemo<string>({
   *   cppExpression: 'thm_font_family.get() + "_" + std::to_string(thm_font_size.get())',
   *   cppReturnType: 'std::string',
   *   dependencies: [...familyDeps, ...sizeDeps],
   * });
   */
  derivedMemo<T>(opts: {
    cppExpression: string;
    cppReturnType: string;
    dependencies: ExpressionDependency[];
  }): ReactiveNode<T> {
    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies: opts.dependencies,
      cppExpression: opts.cppExpression,
      cppReturnType: opts.cppReturnType,
    });
    registerReactiveNode(node);
    return node;
  },

  /**
   * Test whether a reactive numeric value is NaN.
   *
   * Returns a `ReactiveNode<boolean>` that is `true` when the source value
   * is NaN (e.g. HA reports `None` for a numeric attribute).
   *
   * @example
   * // Use with bind.memo to provide a fallback:
   * value={bind.memo(() => bind.isNaN(light.brightness).get() ? 0 : light.brightness.get())}
   */
  isNaN(node: ReactiveNode<number>): ReactiveNode<boolean> {
    const sigName = node.cppSignalName ?? node.dependencies[0]?.cppSignalName;
    const getter = sigName ? `${sigName}.get()` : `memo_${(node as unknown as { _index: number })._index}.get()`;
    return bind.derivedMemo<boolean>({
      cppExpression: `std::isnan(${getter})`,
      cppReturnType: 'bool',
      dependencies: node.dependencies,
    });
  },
};

