// ────────────────────────────────────────────────────────────────────────────
// __espcompose — internal compiler plumbing for reactive data binding
//
// This module is NOT part of the public API. The double-underscore prefix
// signals that it is reserved for compiler-generated code.
//
// The CLI's reactive transformer emits calls to:
//   __espcompose.compiled()     — pre-computed C++ reactive nodes
//   __espcompose.slotted()      — slot-substituted reactive nodes
//   __espcompose.derivedMemo()  — explicit C++ memo construction
// ────────────────────────────────────────────────────────────────────────────

import { ReactiveNode } from './reactive-node';
import type { ExpressionDependency } from './reactive-node';
import type { ExprNode, ExprType } from './ir/expr-types';
import { registerReactiveNode } from './hooks/useReactiveScope';

// ────────────────────────────────────────────────────────────────────────────
// Library format version validation
// ────────────────────────────────────────────────────────────────────────────

/** Format versions this SDK can consume. */
export const SUPPORTED_FORMAT_VERSIONS: readonly number[] = [1];

/**
 * Validate that a compiled library's format version is supported by this SDK.
 * Throws a clear error if the version is missing or incompatible.
 *
 * Libraries stamp `__espcompose_format__` into their entry point at build time.
 * Call this at import time to catch version mismatches early.
 */
export function validateLibraryFormat(version: unknown): void {
  if (typeof version !== 'number') {
    throw new Error(
      'This ESPCompose library was not compiled with format versioning. ' +
      'Rebuild the library with the latest ESPCompose CLI (`espcompose library`).',
    );
  }
  if (!SUPPORTED_FORMAT_VERSIONS.includes(version)) {
    throw new Error(
      `This ESPCompose library was compiled with format v${version}, ` +
      `but this SDK supports format v${SUPPORTED_FORMAT_VERSIONS.join(', v')}. ` +
      'Please rebuild the library with a compatible ESPCompose CLI version.',
    );
  }
}

export const __espcompose = {

  /**
   * Create a ReactiveNode from pre-computed metadata.
   *
   * This is the compile-time entry point — the CLI's reactive transformer
   * AST-compiles expressions and injects calls to this method.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  compiled<T>(meta: {
    type: ExprType;
    deps: Array<{
      sourceId: string;
      triggerType: string;
      sourceDomain: string;
      sourceType?: string;
    }>;
    expr: ExprNode;
  }): ReactiveNode<T> {
    const dependencies: ExpressionDependency[] = meta.deps.map(d => ({
      sourceId: d.sourceId,
      triggerType: d.triggerType,
      sourceDomain: d.sourceDomain,
      sourceType: (d.sourceType as 'ha_entity' | 'theme' | undefined),
    }));

    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies,
      exprType: meta.type,
    });

    node.exprIR = meta.expr;

    registerReactiveNode(node);
    return node;
  },

  /**
   * Create a ReactiveNode from a template with slot placeholders.
   *
   * The compiler emits ExprSlot nodes for Signal<T>-typed subexpressions
   * that can't be resolved statically. At runtime this method resolves
   * the slots using the provided ReactiveNode arguments.
   *
   * @internal — generated by the compiler, not for direct user use.
   */
  slotted<R>(
    meta: { type: ExprType; slots: number; expr: ExprNode },
    ...signals: unknown[]
  ): ReactiveNode<R> {
    const allDeps: ExpressionDependency[] = [];

    for (let i = 0; i < meta.slots; i++) {
      const sig = signals[i] as ReactiveNode<unknown> | undefined;
      if (!sig) continue;
      allDeps.push(...sig.dependencies);
    }

    const node = __espcompose.derivedMemo<R>({
      exprType: meta.type,
      dependencies: allDeps,
      exprIR: resolveExprSlots(meta.expr, signals as ReactiveNode[]),
    });

    return node;
  },

  /**
   * Create a derived memo with an explicit ExprIR expression.
   *
   * Use this when the expression IR is already known and doesn't need
   * to go through the compiler transform (e.g. internal generated code).
   */
  derivedMemo<T>(opts: {
    exprType: ExprType;
    dependencies: ExpressionDependency[];
    exprIR: ExprNode;
  }): ReactiveNode<T> {
    const node = new ReactiveNode<T>({
      kind: 'memo',
      dependencies: opts.dependencies,
      exprType: opts.exprType,
    });
    node.exprIR = opts.exprIR;
    registerReactiveNode(node);
    return node;
  },
};

/**
 * Walk an ExprNode tree and replace ExprSlot nodes with resolved entity/theme
 * references from the provided signal ReactiveNodes.
 */
function resolveExprSlots(expr: ExprNode, signals: ReactiveNode[]): ExprNode {
  if (expr.kind === 'slot') {
    const sig = signals[expr.slotIndex];
    if (!sig) return expr;
    // If the signal already has exprIR, use it directly
    if (sig.exprIR) return sig.exprIR;
    // Resolve from dependency metadata
    const dep = sig.dependencies[0];
    if (dep?.sourceType === 'theme') {
      const path = dep.sourceId === '__theme__' ? dep.triggerType : '';
      return { kind: 'theme_read', path, type: sig.exprType ?? 'float' };
    }
    // Default: entity prop
    const sourceId = sig.sourceId ?? dep?.sourceId ?? '';
    const property = sig.property ?? 'value';
    return { kind: 'entity_prop', entityId: sourceId, property, type: sig.exprType ?? 'float' };
  }

  // Recursively resolve children
  switch (expr.kind) {
    case 'binary':
      return { ...expr, left: resolveExprSlots(expr.left, signals), right: resolveExprSlots(expr.right, signals) };
    case 'unary':
    case 'postfix':
      return { ...expr, operand: resolveExprSlots(expr.operand, signals) };
    case 'ternary':
      return { ...expr, test: resolveExprSlots(expr.test, signals), consequent: resolveExprSlots(expr.consequent, signals), alternate: resolveExprSlots(expr.alternate, signals) };
    case 'call':
      return { ...expr, args: expr.args.map(a => resolveExprSlots(a, signals)) };
    case 'concat':
      return { ...expr, parts: expr.parts.map(p => resolveExprSlots(p, signals)) };
    case 'to_string':
      return { ...expr, expr: resolveExprSlots(expr.expr, signals) };
    case 'group':
      return { ...expr, expr: resolveExprSlots(expr.expr, signals) };
    case 'resolve_font':
      return { ...expr, family: resolveExprSlots(expr.family, signals), size: resolveExprSlots(expr.size, signals) };
    default:
      return expr;
  }
}
