/**
 * LVGL style definition ID constants.
 *
 * Every design-system component references these IDs via the LVGL `styles:`
 * prop instead of inlining visual values.  The IDs correspond 1-to-1 with
 * entries generated by `themeToStyleDefinitions()` in `bridge.ts`.
 *
 * Naming: `ds_{category}[_{variant}]`
 * NOTE: ESPHome requires underscores in IDs — dashes are not allowed.
 */

import type { StatusToken, TextVariant } from './types';

// ── Surface / background ────────────────────────────────────────────────────

export const STYLE_BG          = 'ds_bg';
export const STYLE_SURFACE     = 'ds_surface';
export const STYLE_SURFACE_ALT = 'ds_surface_alt';
export const STYLE_BORDER      = 'ds_border';

// ── Text ────────────────────────────────────────────────────────────────────

export const STYLE_TEXT_PRIMARY   = 'ds_text_primary';
export const STYLE_TEXT_SECONDARY = 'ds_text_secondary';
export const STYLE_TEXT_DISABLED  = 'ds_text_disabled';

/** Typography variant style IDs. */
export const STYLE_TEXT_VARIANT: Record<TextVariant, string> = {
  title:    'ds_text_title',
  subtitle: 'ds_text_subtitle',
  body:     'ds_text_body',
  caption:  'ds_text_caption',
};

// ── Status × variant ────────────────────────────────────────────────────────

type ButtonVariant = 'solid' | 'outline';

/** Style ID for a status button container. */
export function statusStyleId(status: StatusToken, variant: ButtonVariant): string {
  return `ds_status_${status}_${variant}`;
}

/** Style ID for a status button's inner label text. */
export function statusTextStyleId(status: StatusToken, variant: ButtonVariant): string {
  return `ds_status_${status}_${variant}_text`;
}

/** All status tokens, used for iteration when generating definitions. */
export const ALL_STATUSES: readonly StatusToken[] = [
  'primary', 'secondary', 'success', 'warning', 'danger',
] as const;

/** All button variants, used for iteration. */
export const ALL_BUTTON_VARIANTS: readonly ButtonVariant[] = ['solid', 'outline'] as const;

// ── Widget parts ────────────────────────────────────────────────────────────

export const STYLE_SLIDER_INDICATOR = 'ds_slider_indicator';
export const STYLE_SLIDER_KNOB      = 'ds_slider_knob';
export const STYLE_SWITCH_INDICATOR = 'ds_switch_indicator';
export const STYLE_SWITCH_KNOB      = 'ds_switch_knob';
export const STYLE_ARC_INDICATOR    = 'ds_arc_indicator';
export const STYLE_ARC_KNOB         = 'ds_arc_knob';
